server:
  port: 8082
openapi:
  clientId: 05644454-d465-47fb-ad25-140cd45c0792
  clientSecret: VhuogEiOxWHaGwqZWRPsIRfAodvlgLwfrvaCGXJuFgwSajDKWMDcikoGNjjJMSgW
  tokenUrl: https://id.mercedes-benz.com/as/token.oauth2
  redirectUri: http://localhost:3000/oauth2/redirect
  apiUrl: https://api.mercedes-benz.com/experimental/connectedvehicle/v2

mercedes:
  carId : B2841247C0AA2C1E97
  scheduleDelayInMillis: 10000
  initialDelayInMillis: 150000
